#!/usr/bin/env python3
"""
Print the answer key for the seeded challenge set.

    python3 scripts/show_seed_flags.py

Reads instance/seed_flags.json, which the seeder writes 0600 on first boot.
Challenges marked PER-PLAYER ship a flag.txt, so the runner mints a fresh flag
for every player at launch and the value shown here is only a fallback — do not
read it out expecting anyone else's submission to match.

Do not put this on a projector.
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

STORE = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                     'instance', 'seed_flags.json')


def main() -> int:
    if not os.path.isfile(STORE):
        print(f'No flag store at {STORE}.')
        print('Start the platform once — the seeder writes it on first boot.')
        return 1

    with open(STORE) as fh:
        store = json.load(fh)

    try:
        import challenges
        specs = {s['slug']: s for s in challenges.all_specs()}
    except Exception:
        specs = {}

    print()
    print('  CSIA GYM — seeded challenge answer key')
    print('  ' + '-' * 86)
    print(f'  {"CATEGORY":<22}{"CHALLENGE":<20}{"FLAG":<44}')
    print('  ' + '-' * 86)

    for slug in sorted(store, key=lambda s: list(specs).index(s) if s in specs else 99):
        spec = specs.get(slug, {})
        flag = store[slug]
        if spec.get('dynamic_flag'):
            flag = 'per-player, minted at launch'
        print(f'  {spec.get("category", "?"):<22}{spec.get("title", slug):<20}{flag:<44}')

    print('  ' + '-' * 86)
    print('  Per-player flags are generated by the runner when a player presses Launch.')
    print('  To see one for yourself, launch the instance on your own account and solve it.')
    print()
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
